website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from .models import User, Post, Like
from sqlalchemy.orm import joinedload
from sqlalchemy import or_
from . import db
import datetime


# Define the views blueprint
views = Blueprint('views', __name__)


# Define a route for the home page
@views.route('/home/', methods=['GET', 'POST'])
@login_required 
def home():
    """
    Renders the home page of the website.
    If the request method is POST, it checks for a search query in the form data.
    If a search query is provided, it redirects to the search page.
    Otherwise, it retrieves all posts from the database and renders the home.html template.
    Returns:
        The rendered home.html template with the current user and retrieved posts.
    """
    if request.method == "POST":
        # Get the search query from the form
        search_query = request.form.get("search")
        if search_query:
            return redirect(url_for("views.search", search=search_query))
    # Retrieve all posts from the database, along with the associated user information
    posts = db.session.query(Post, User).join(User, Post.user_id == User.id).order_by(Post.date.desc()).all()
    return render_template("home.html", user=current_user, page="Home", posts=posts)


# Define a route for the profile page
@views.route('/profile/')
@login_required
def profile_redirect():
    """
    Redirects to the profile page of the current user.
    Returns:
        A redirect response to the profile page.
    """
    return redirect('/profile/%s' % current_user.id)


@views.route('/profile/<int:id>', methods=["GET","POST"])
@login_required
def user_profile(id):
    """
    Renders the profile page of a specific user.
    If the request method is GET, it retrieves the user information and posts from the database and renders the user_profile.html template.
    If the request method is POST, it checks for a new post in the form data and adds it to the database.
    Args:
        id: The ID of the user.
    Returns:
        The rendered user_profile.html template with the user information and posts.
    """
    if request.method == "GET":
        # Retrieve user information and posts from the database
        user = User.query.get(id)
        posts = Post.query.filter_by(user_id=id).order_by(Post.date.desc()).all()
        name = f"{user.first_name} {user.last_name}"
        date_joined = datetime.datetime.strptime(str(user.date_joined), '%Y-%m-%d %H:%M:%S').strftime('%B %d, %Y')
        return render_template("user_profile.html", page="Your Profile", name=name, user=user, id=id, date_joined=date_joined, posts=posts, current_user=current_user)
    elif request.method == "POST":
        # Check for a new post in the form data and add it to the database
        post = request.form.get("post")
        if post is not None:
            new_post = Post(data=post, user_id=current_user.id)
            db.session.add(new_post)
            db.session.commit()
        return redirect(f'/profile/{id}')


# Define a route for redirecting to the edit profile page
@views.route('/edit/profile/')
@login_required
def redirect_to_edit_profile():
    """
    Redirects to the edit profile page of the current user.
    Returns:
        A redirect response to the edit profile page.
    """
    return redirect("/edit/profile/%s" % current_user.id)


# Define a route for viewing a specific post
@views.route('/post/<int:id>', methods=['GET','POST'])
@login_required
def view_post(id):
    """
    Renders the view post page for a specific post.
    If the request method is GET, it retrieves the post information and renders the view_post.html template.
    If the request method is POST, it checks for a like or unlike action in the form data and updates the like status in the database.
    Args:
        id: The ID of the post.
    Returns:
        The rendered view_post.html template with the post information.
    """
    # Retrieve the post information from the database
    post = Post.query.options(joinedload(Post.user)).get(id)
    if not post:
        return render_template("404.html", error="This post doesn't exist.", current_user=current_user)

    liked = Like.query.filter_by(user=current_user, post=post).first()
    # Extract the date from the post and format it
    date = str(post.date).split(" ")[0]
    return render_template("view_post.html", page="Post", post=post, liked=liked, date=date)


# Define a route for deleting a post
@views.route('/delete/post/<int:id>')
@login_required
def delete_post(id):
    """
    Delete a post with the given ID.
    Args:
        id (int): The ID of the post to be deleted.
    Returns:
        redirect: Redirects to the user's profile page.
    Raises:
        None
    """
    # Retrieve the post from the database
    post = Post.query.get(id)
    if post is None:
        flash("Post not found.", category="error")
        return redirect(url_for("views.home"))
    try:
        # Check if the current user is the owner of the post
        if current_user.id == post.user_id:
            # Delete the post from the database
            db.session.delete(post)
            db.session.commit()
            flash("Post deleted.", category="success")
        else:
            flash("You can only delete your own posts.", category="error")
    except Exception as e:
        flash("An error occurred while deleting the post.", category="error")
        print(e)
    return redirect("/profile/")


@views.route('/search/')
@login_required
def empty_search_handler():
    """
    Redirects the user to the previous page.
    This function is used as a handler for the '/search/' route. It redirects the user to the previous page they were on.
    Returns:
        redirect: A redirect response to the previous page.
    """
    previous_page = request.referrer
    return redirect(previous_page)


@views.route("/search/<search>", methods=['GET','POST'])
@login_required
def search(search):
    """
    Search function to handle search requests.
    Args:
        search (str): The search query.
    Returns:
        render_template: The rendered search.html template with search results.
    """
    if request.method == "POST":
        if request.form.get("search") != None:
            search = request.form.get('search')
            return redirect("/search/%s" % search)
    else:
        # Retrieve posts that match the search query
        posts = db.session.query(Post, User).join(User, Post.user_id == User.id).filter(
            or_(Post.data.ilike(f"%{search}%"))).all()
        full_name = User.first_name + " " + User.last_name
        if len(search) > 2:
            # Retrieve users that match the search query
            users = User.query.filter(
                or_(User.first_name.ilike(f"%{search}%"), User.last_name.ilike(f"%{search}%"), full_name.ilike(f"%{search}%"))).all()
        else:
            users = None
        return render_template('search.html', posts=posts, users=users, query=search, user=current_user, current_user=current_user, page="Search")


@views.route('/post/<int:post_id>/like', methods=["POST"])
@login_required
def like_post(post_id):
    """
    Like or unlike a post.
    Args:
        post_id (int): The ID of the post to like or unlike.
    Returns:
        redirect: Redirects the user to the previous page after the like/unlike operation.
    """
    # Get the previous page URL
    previous_page = request.referrer

    post = Post.query.get_or_404(post_id)
    # Check if the user has already liked the post
    like = Like.query.filter_by(user=current_user, post=post).first()
    if like:
        db.session.delete(like)
    else:
        like = Like(user=current_user, post=post)
        db.session.add(like)
    db.session.commit()
    return redirect(previous_page)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% block head %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/base.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/home.css') }}"
    />

    {% block extra_css %}{% endblock %}

    <title>{% block title %}Quotes | {{page}}{% endblock %}</title>
  </head>
  {% endblock %}
  <body>
    {% if user.is_authenticated %}
    <nav
      class="navbar navbar-expand-lg"
      data-bs-theme="dark"
      style="background: transparent !important; width: 100%; z-index: 1000"
    >
      <div class="container-fluid">
        <!-- Define the website logo and link -->
        <a class="navbar-brand" href="/home/"> Quotes </a>
        <!-- Define the navbar toggler button -->
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Define the navbar collapse section -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Define the search form -->
          <form
            action=""
            method="post"
            class="d-flex ms-auto custom-search-form"
          >
            <!-- Define the search input field -->
            <input
              type="text"
              class="form-control custom-search-input"
              aria-label="Search"
              aria-describedby="button-addon2"
              name="search"
              placeholder="Search"
            />
            <!-- Define the search button -->
            <button
              class="btn btn-outline-light custom-search-button"
              type="submit"
              id="button-addon2"
            >
              <!-- Use a Font Awesome icon for the search button -->
              <i class="fas fa-search"></i> Search
            </button>
          </form>
          <!-- Define the navigation items -->
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <!-- Define the navigation item for the user's profile -->
            <li class="nav-item">
              <a class="nav-link" href="/profile/">
                <!-- Display the user's profile picture -->
                <img
                  src="../static/images/{{user.profile_picture}}"
                  alt="Profile"
                  class="profile-photo"
                />
                Profile
              </a>
            </li>
            <!-- Define the navigation item for the settings page -->
            <li class="nav-item">
              <a class="nav-link" href="/edit/profile/">
                <!-- Use a Font Awesome icon for the settings link -->
                <i class="fas fa-cog"></i> Settings
              </a>
            </li>
            <!-- Define the navigation item for logging out -->
            <li class="nav-item">
              <a class="nav-link" href="/logout">
                <!-- Use a Font Awesome icon for the logout link -->
                <i class="fas fa-sign-out-alt"></i> Logout
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% else %}
    {% endif %}
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <!-- Display an error alert message -->
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
      {{ message }}
      <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
      ></button>
    </div>
    {% elif category == 'primary' %}
    <!-- Display a primary alert message -->
    <div class="alert alert-primary alert-dismissable fade show" role="alert">
      {{ message }}
      <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
      ></button>
    </div>
    {% else %}
    <!-- Display a success alert message -->
    <div class="alert alert-success alert-dismissable fade show" role="alert">
      {{ message }}
      <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
      ></button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% block body %}{% endblock %}

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
      integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/create_post.html
{% extends 'base.html' %} {% block body %}
<div class="container">
  <div class="container">
    <!-- FORM -->
    <form method="post">
      <!-- Textarea for user input -->
      <textarea
        name="post"
        cols="30"
        rows="10"
        class="form-control"
        placeholder="Write a post here..."
        maxlength="10000"
        required
      ></textarea>
      <br />
      <!-- Submit button to create the post -->
      <input
        type="submit"
        value="Create Post"
        class="form-control btn btn-primary"
      />
    </form>
  </div>
</div>
{% endblock %}

website/templates/edit_user_profile.html
{% extends 'base.html' %}

{% block extra_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/settings.css') }}">
{% endblock %}

{% block body %}
<div class="tcontainer">
  <center>
    <br>
    <h1 style="color:black;">Settings</h1>
    <form method="post">
      <table class="table">
        <!-- First Name and Last Name Row -->
        <tr>
          <td class="signup-boxes" colspan="2">
            <label for="first_name">First Name:</label>
            <input
              type="text"
              name="first_name"
              id="first_name"
              placeholder="First Name"
              class="form-control"
              value="{{current_user.first_name}}"
            />
          </td>
          <td class="signup-boxes" colspan="2">
            <label for="last_name">Last Name:</label>
            <input
              type="text"
              name="last_name"
              id="last_name"
              placeholder="Last Name"
              class="form-control"
              value="{{current_user.last_name}}"
            />
          </td>
        </tr>
        <!-- Email Row -->
        <tr>
          <td class="signup-boxes" colspan="4">
            <label for="email">Email:</label>
            <input
              type="email"
              name="email"
              id="email"
              placeholder="Email"
              class="form-control"
              value="{{current_user.email}}"
            />
          </td>
        </tr>
        <!-- Old Password Row -->
        <tr>
          <td class="signup-boxes" colspan="4">
            <label for="old_password">Old Password:</label>
            <input
              type="password"
              name="old_password"
              id="old_password"
              placeholder="Type your old password"
              class="form-control"
            />
          </td>
        </tr>
        <!-- New Password and Confirm New Password Row -->
        <tr>
          <td class="signup-boxes" colspan="2">
            <label for="password1">New Password:</label>
            <input
              type="password"
              name="password1"
              id="password1"
              placeholder="New Password"
              class="form-control"
            />
          </td>
          <td class="signup-boxes" colspan="2">
            <label for="password2">Type new password again:</label>
            <input
              type="password"
              name="password2"
              id="password2"
              placeholder="Type new password again"
              class="form-control"
            />
          </td>
        </tr>
        <!-- Bio Row -->
        <tr>
          <td class="signup-boxes" colspan="4">
            <label for="bio">Your Bio:</label>
            {% if current_user.bio == None or current_user.bio == "" %}
            <textarea name="bio" id="bio" cols="30" rows="10" placeholder="Enter your bio" class="form-control"></textarea>
            {% else %}
            <textarea name="bio" id="bio" cols="30" rows="10" placeholder="Enter your bio (max 1,500 characters). Markup (HTML) supported." class="form-control" maxlength="1500">{{current_user.bio}}</textarea>
            {% endif %} 
          </td>
        </tr> 
        <!-- Update Profile Button Row -->
        <tr>
          <td class="signup-boxes" colspan="4">
            <input
              type="submit"
              class="btn btn-primary form-control signup-boxes update"
              value="Update Profile"
            />
          </td>
        </tr>
      </table>
    </form>
    <br><br>
    <a href="/edit/profile/{{current_user.id}}/images" class="btn btn-outline-primary">Change Profile Picture</a>
    <a href="/logout" class="btn btn-outline-danger">Log Out</a>
    <br><br><br><br>
  </center>
</div>
{% endblock %}

website/templates/edit_user_profile_picture.html
{% extends 'base.html' %}

{% block body %}
<br><br>
<link rel="stylesheet" href="{{ url_for('static', filename='css/profilepic.css') }}">

<div class="pcontainer">
  <div class="pic">
    <!-- Display the user's profile picture if it exists -->
    {% if user.profile_picture %}
    <img
      src="/static/images/{{user.profile_picture}}"
      alt="Avatar Image"
      style="border-radius: 50%; width: 150px; height: 150px"
    />
    {% else %}
    <!-- Display a default profile picture if the user does not have one -->
    <img
      src="/static/images/default_profile_photo.jpg"
      alt="Avatar Image"
      style="border-radius: 50%; width: 150px; height: 150px"
    />
    {% endif %}
  </div>

  <div class="edit">
    <form
      action="/edit/profile/{{user.id}}/images/"
      method="post"
      enctype="multipart/form-data"
    >
      <!-- Allow the user to upload a new profile picture -->
      <input
        type="file"
        id="img"
        name="profile_picture"
        accept="image/*"
        class="form-control"
      />
      <br />
      <input type="submit" class="btn btn-primary form-control" />
    </form>
  </div>

  <div class="remove">
    <!-- Allow the user to remove their profile picture -->
    <a
      href="/edit/profile/{{user.id}}/remove_profile_picture/"
      class="btn btn-sm btn-outline-primary"
    >Remove Profile Photo</a>
  </div>
</div>

{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block body %}
<div class="container">
  {% for post, user in posts %}
  <div class="border">
    <!-- User Profile Picture -->
    <a href="/profile/{{user.id}}">
      <img
        src="../static/images/{{user.profile_picture}}"
        alt="Avatar Image"
        class="photo"
        style="margin-right: 5px; border-radius: 50%; width: 30px;"
      />
    </a>

    <!-- User Full Name -->
    <a href="/profile/{{user.id}}" style="color: #020202; text-decoration: none;">
      {{ user.first_name }} {{ user.last_name }}
    </a>

    <!-- Post Data -->
    <p class="post-data">{{ post.data }}</p>

    <!-- Liking Post Form -->
    <form action="/post/{{post.id}}/like" method="post" class="like">
      <button type="submit" class="btn btn-outline-dark btn-sm">🤍</button>
      <p style="display: inline">{{ post.likes | count }}</p>
    </form>
  </div>
  <br />
  {% endfor %}
</div>
{% endblock %}

website/templates/login_page.html
{% extends 'base.html' %}

{% block extra_css %}
<link rel="stylesheet" href="../static/css/login.css">
{% endblock %}

{% block body %}
<!-- Login table -->
<table class="login-table">

  <!-- Table row for heading -->
  <tr class="txt">
    <td colspan="2">
      <h1>Login</h1>
    </td>
  </tr>

  <!-- Table row for login form -->
  <tr>
    <td class="login-th">
      <div class="input-group mb-3">
        <form action="" method="post">

          <!-- Email input field -->
          <input
            type="email"
            name="email"
            placeholder="email address"
            class="form-control"
          />

          <!-- Password input field -->
          <input
            type="password"
            name="password"
            placeholder="password"
            class="form-control"
          />

          <!-- Submit button -->
          <span class="d-grid gap-2">
            <input type="submit" class="btn btn-primary form-control" value="Log In" />
          </span>
        </form>
      </div>

      <!-- Sign up link -->
      <p class="form-text">Don't have an account?
        <a href="sign-up" class="form-text" style="color:black">Sign Up</a>
      </p>
    </td>
  </tr>
</table>
{% endblock %}

website/templates/search.html
{% extends 'base.html' %} {% block body %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/search.css') }}"
/>

<div class="searchcontainer">
  <div class="show">
    <h2>Showing results for "{{query}}"</h2>
  </div>

  <div class="user">
    <h3>Users</h3>
    {% if users %} {% for user in users %}
    <div class="border" style="border-radius: 10px; padding: 5px">
      <strong
        ><a href="/profile/{{ user.id }}" style="color: black"
          >{{ user.first_name }} {{ user.last_name }}</a
        ></strong
      >
    </div>
    {% endfor %} {% else %} There are no users matching your search. <br />
    {% endif %}
    <br />
  </div>

  <div class="postsearch">
    <h3>Posts</h3>
    {% if posts %} {% for post, user in posts %}
    <div class="border_p" style="border-radius: 10px; padding: 5px">
      <small
        ><a
          href="/profile/{{user.id}}"
          style="color: #6e8898; text-decoration: none"
          >{{ user.first_name }} {{ user.last_name }}</a
        ></small
      >
      <p>{{ post.data }}</p>
      {% if current_user.id == post.user_id %}
      <!-- Handle specific condition here -->
      {% else %}
      <!-- Handle other condition here -->
      {% endif %}
      <form
        action="/post/{{post.id}}/like"
        method="post"
        style="display: inline"
      >
        <input type="submit" class="btn btn-outline-like btn-sm" value="🤍" />
        <p style="display: inline">{{ post.likes | count }}</p>
      </form>
    </div>
    <br />
    {% endfor %} {% else %} There are no posts matching your search. {% endif %}
  </div>
</div>

{% endblock %}

website/templates/signup_page.html
{% extends 'base.html' %}

{% block extra_css %}
  <!-- Include the CSS file for the signup page -->
  <link rel="stylesheet" href="../static/css/signup.css"/>
{% endblock %}

{% block body %}
<div class="signup-page">
  <br /><br />
  <form action="" method="post">
    <table class="signup-table">
      <tr>
        <td class="signup-boxes" colspan="2" style="text-align: center;">
          <h1>Get in touch</h1>
        </td>
      </tr>
      <tr>
        <td class="signup-boxes">
          <!-- Input field for first name -->
          <input
            type="text"
            name="first_name"
            placeholder="First Name"
            class="form-control"
            value="{{form_first_name}}"
          />
        </td>
      </tr>
      <tr>
        <td class="signup-boxes">
          <!-- Input field for last name -->
          <input
            type="text"
            name="last_name"
            placeholder="Last Name"
            class="form-control"
            value="{{form_last_name}}"
          />
        </td>
      </tr>
      <tr>
        <td class="signup-boxes">
          <!-- Input field for email -->
          <input
            type="email"
            name="email"
            placeholder="Email"
            class="form-control"
            value="{{form_email}}"
          />
        </td>
      </tr>
      <tr>
        <td class="signup-boxes">
          <!-- Input field for password -->
          <input
            type="password"
            name="password1"
            placeholder="Create a Password"
            class="form-control"
          />
        </td>
      </tr>
      <tr>
        <td class="signup-boxes">
          <!-- Input field for password confirmation -->
          <input
            type="password"
            name="password2"
            placeholder="Type password again for confirmation"
            class="form-control"
          />
        </td>
      </tr>
      <tr>
        <td class="signup-boxes">
          <!-- Submit button -->
          <input
            type="submit"
            class="btn btn-primary form-control"
            value="Sign Up"
          />
        </td>
      </tr>
      <tr>
        <td class="signup-boxes">
          <!-- Link to login page -->
          <a href="/" class="login">Log in</a>
        </td>
      </tr>
    </table>
  </form>
</div>
</center>
{% endblock %}

website/templates/user_profile.html
{% extends 'base.html' %} {%block body%}
<!-- Linking the CSS file -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/userprofile.css') }}">

<div class="profile_container">
  <h2>
    {% if user.profile_picture %}
    <!-- Displaying the user's profile picture -->
    <img src="../static/images/{{user.profile_picture}}" alt="Avatar Image" 
    style="border-radius: 50%; margin-left: 30px; width: 100px; height: 100px">
    {% else %}
    <!-- Displaying a default profile picture if the user doesn't have one -->
    <img
      src="../static/images/default_profile_photo.jpg"
      alt="Avatar image" 
      style="border-radius: 50%; margin-left: 30px; width: 100px; height: 100p;"
    /> {% endif %}
  </h2>
  <span class="name" >{{name}}</span>
  <br>
  {% if id == current_user.id %}
  <!-- Link to edit the user's profile -->
  <a
    href="/edit/profile"
    class="btn btn-secondary btn-sm"
    >Edit your profile</a
  >
  <div class="bio">
    <h5>Bio</h5>
    {% if user.bio == None or user.bio == "" %}
      <!-- Displaying a message if the user doesn't have a bio -->
      <p>This user has no bio.</p>
    {% else %}
      <div class="bio-content">
        <p>{{ user.bio }}</p>
      </div>
  </div>
  {% endif %}
  <br /><br />
  <div class="container_post">
    <!-- Post creation form -->
    <form method="post">
        <textarea name="post" id="po" cols="50" rows="10" 
          class="form-control" placeholder="Write a post here..." 
          maxlength="300" required></textarea>
        <br />
        <input type="submit" value="Create Post" class="form-control btn btn-primary" />
    </form>
</div>
  {% else %} {% endif %} <br />
  <h4 style="margin-left: 620px;">Recent Posts</h4>
  {% if posts %}{% else %}
  <!-- Displaying a message if the user has no posts -->
  <p>This user has no posts.</p>
  {% endif %} {% for post in posts %}
  <div class="border_p" style="border-radius: 10px; padding: 5px">
    <div class="p">
    <p>{{ post.data }}</p>
    </div>
    <small
      >{% if id == current_user.id %}
      <!-- Link to delete a post -->
      <a
        href="{{ url_for('views.delete_post', id=post.id) }}"
        onclick="return confirm('Are you sure you want to delete this post?')"
        class="btn btn-sm btn-warning"
        >Delete Post</a
      ></small
    >{% endif %}
    <!-- Liking Post -->
    <form action="/post/{{post.id}}/like" method="post" style="display: inline">
      <input type="submit" class="btn btn-outline-like btn-sm" value="🤍" />
      <p style="display: inline">{{ post.likes | count }}</p></form>
    </form>
  </div>
  <br/>
  {% endfor %}

  <br />

  <div class="date">
    <p><b>Date Joined: </b>{{date_joined}}</p>
  </div>
</div>
{%endblock%}